### PR TITLE
add section with toy example on domonster function for use with existing panda/other GRN

### PR DESCRIPTION
**Pull request by laurenhsu1**

### CODE REVIEW

**Comment by marouenbg** [comment]
@laurenhsu1 Can you check on Netbooks that your code appears and works correctly on the server?

**Comment by marouenbg** [comment]
I am not sure but the cells seem hidden to me

**Comment by laurenhsu1** [comment]
I am forbidden from netbooks :(

**Comment by marouenbg** [comment]
@laurenhsu1 Fixed now!

**Comment by laurenhsu1** [comment]
@marouenbg it initially showed up with hidden cells, but now it is showing fine. I think either way is fine and it would also be ok with hidden cells since it's not really part of the yeast cc vignette, and rather is meant more to show examples of inputs?

**Pull request merged**
